export const procrastinationQuotes = [
  "Procrastination is opportunity's assassin. - Victor Kiam",
  "The best way to get something done is to begin. - Author Unknown",
  "You don't have to see the whole staircase, just take the first step. - Martin Luther King Jr.",
  "You may delay, but time will not. - Benjamin Franklin",
  "Procrastination is the thief of time. - Edward Young",
  "The perfect time to start something never arrives. - Author Unknown",
  "Tomorrow is often the busiest day of the week. - Spanish Proverb",
  "I'll think about that tomorrow. - Scarlett O'Hara (Gone with the Wind)",
  "The greatest amount of wasted time is the time not getting started. - Dawson Trotman",
  "The sooner I fall behind, the more time I have to catch up. - Anonymous",
  "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along. - Napoleon Hill",
  "How soon 'not now' becomes 'never.' - Martin Luther",
  "Procrastination makes easy things hard and hard things harder. - Mason Cooley",
  "Begin doing what you want to do now. We are not living in eternity. We have only this moment, sparkling like a star in our hand - and melting like a snowflake. - Francis Bacon Sr.",
  "You cannot escape the responsibility of tomorrow by evading it today. - Abraham Lincoln",
  "The greatest thief this world has ever produced is procrastination, and he is still at large. - Josh Billings",
  "The best way to predict the future is to create it. - Peter Drucker",
  "You can't get much done in life if you only work on the days when you feel good. - Jerry West",
  "Nothing is so fatiguing as the eternal hanging on of an uncompleted task. - William James",
  "One of these days is none of these days. - Proverb",
  "If you want to make an easy job seem mighty hard, just keep putting off doing it. - Olin Miller",
  "The only difference between success and failure is the ability to take action. - Alexander Graham Bell",
  "The best way to overcome procrastination is to do it. - Author Unknown",
  "It's not that I'm so smart, it's just that I stay with problems longer. - Albert Einstein",
  "The habit of always putting off an experience until you can afford it, or until the time is right, or until you know how to do it is one of the greatest burglars of joy. Be deliberate, but once you've made up your mind, jump in. - Charles R. Swindoll",
  "You can't start the next chapter of your life if you keep re-reading the last one. - Author Unknown",
  "If you want to make an easy job seem mighty hard, just keep putting off doing it. - Olin Miller",
  "Begin while others are procrastinating. Work while others are wishing. - William Arthur Ward",
  "You cannot plough a field by turning it over in your mind. - Unknown",
  "The two rules of procrastination: 1) Do it today. 2) Tomorrow will be today tomorrow. - Author Unknown",
  "A year from now, you may wish you had started today. - Karen Lamb",
  "The time for action is now. It's never too late to do something. - Carl Sandburg",
  "Success is not obtained overnight. It comes in installments; you get a little bit today, a little bit tomorrow until the whole package is given out. The day you procrastinate, you lose that day's success. - Israelmore Ayivor",
  "Tomorrow is only found in the calendar of fools. - Og Mandino",
  "Procrastination is the grave in which opportunity is buried. - Unknown",
  "You cannot escape the responsibility of tomorrow by evading it today. - Abraham Lincoln",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The best way to predict your future is to create it. - Peter Drucker",
  "Do not wait for leaders; do it alone, person to person. - Mother Teresa",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
  "The greatest amount of wasted time is the time not getting started. - Dawson Trotman",
  "The time you enjoy wasting is not wasted time. - Bertrand Russell",
];
